name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.3

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install flake8 pyright pytest pytest-cov bandit
        pip install -r requirements.txt

    - name: Run flake8
      run: |
        flake8 .

    - name: Run pyright
      run: |
        pyright .

    - name: Run pytest
      run: |
        pytest tests/

    - name: Run pytest-cov
      run: |
        pytest --cov=. tests/ --cov-fail-under=70 --cov-report=xml:reports/coverage.xml

    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./reports/coverage.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true

    - name: Run Bandit Report
      uses: jpetrucciani/bandit-check@main
      with:
        bandit_flags: '-r -ll -o ./reports/bandit.html -f html'

    - name: Create bandit output artifact
      uses: actions/upload-artifact@v3
      with:
        name: bandit-security-report
        path: ./reports/bandit.html

  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
