name: Deploy to GitHub pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx

      - name: Build HTML
        run: |
          sphinx-build -b html docs/source/ docs/build/

      - name: Create repo and commit all
        run: |
          cd docs/build
          git config --global user.email "lukewgregory@gmail.com"
          git config --global user.name "L7G9"
          git config --global init.defaultBranch "main"
          git init
          git add -A
          git commit -m 'deploy'

      - name: Push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build

